#include "Arduino.h"

extern "C" {
    void initVariant() {
        // Optional: initialize peripherals or pin states here
    }
}

// Digital pin to port mapping
const PinDescription g_APinDescription[] = {
    // D0 - RX
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_0, PIO_INPUT, (PIN_ATTR_DIGITAL | PIN_ATTR_SERIAL_RX), ADC_CHANNEL_NONE, PWM_CHANNEL_NONE },

    // D1 - TX
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_1, PIO_OUTPUT, (PIN_ATTR_DIGITAL | PIN_ATTR_SERIAL_TX), ADC_CHANNEL_NONE, PWM_CHANNEL_NONE },

    // D2–D13
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_2, PIO_OUTPUT, PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D2
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_3, PIO_OUTPUT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM, ADC_CHANNEL_NONE, PWM_CHANNEL_0 }, // D3
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_4, PIO_OUTPUT, PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D4
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_5, PIO_OUTPUT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM, ADC_CHANNEL_NONE, PWM_CHANNEL_1 }, // D5
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_6, PIO_OUTPUT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM, ADC_CHANNEL_NONE, PWM_CHANNEL_2 }, // D6
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_7, PIO_OUTPUT, PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D7
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_8, PIO_OUTPUT, PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D8
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_9, PIO_OUTPUT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM, ADC_CHANNEL_NONE, PWM_CHANNEL_3 }, // D9
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_10, PIO_OUTPUT, PIN_ATTR_DIGITAL | PIN_ATTR_PWM, ADC_CHANNEL_NONE, PWM_CHANNEL_4 }, // D10
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_11, PIO_OUTPUT, PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D11 (MOSI)
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_12, PIO_INPUT,  PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D12 (MISO)
    { PSEL_PORT::PSEL_PORT_0, PSEL_PIN::PSEL_PIN_13, PIO_OUTPUT, PIN_ATTR_DIGITAL, ADC_CHANNEL_NONE, PWM_CHANNEL_NONE }, // D13 (SCK / LED)

    // A0–A5
    { PSEL_PORT::PSEL_PORT_1, PSEL_PIN::PSEL_PIN_0, PIO_ANALOG, PIN_ATTR_ANALOG, ADC_CHANNEL_0, PWM_CHANNEL_NONE }, // A0
    { PSEL_PORT::PSEL_PORT_1, PSEL_PIN::PSEL_PIN_1, PIO_ANALOG, PIN_ATTR_ANALOG, ADC_CHANNEL_1, PWM_CHANNEL_NONE }, // A1
    { PSEL_PORT::PSEL_PORT_1, PSEL_PIN::PSEL_PIN_2, PIO_ANALOG, PIN_ATTR_ANALOG, ADC_CHANNEL_2, PWM_CHANNEL_NONE }, // A2
    { PSEL_PORT::PSEL_PORT_1, PSEL_PIN::PSEL_PIN_3, PIO_ANALOG, PIN_ATTR_ANALOG, ADC_CHANNEL_3, PWM_CHANNEL_NONE }, // A3
    { PSEL_PORT::PSEL_PORT_1, PSEL_PIN::PSEL_PIN_4, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_DIGITAL, ADC_CHANNEL_4, PWM_CHANNEL_NONE }, // A4 (SDA)
    { PSEL_PORT::PSEL_PORT_1, PSEL_PIN::PSEL_PIN_5, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_DIGITAL, ADC_CHANNEL_5, PWM_CHANNEL_NONE }, // A5 (SCL)
};

const uint32_t g_PinCount = sizeof(g_APinDescription) / sizeof(g_APinDescription[0]);